### ISSUE TITLE
Make the call schema more readable

### ISSUE THREAD

**Issue by jake-lindsay-tfs** [0x41424142/qualysdk#176]
**Is your feature request related to a problem? Please describe.**
The call schema file is currently massive, and while organized by module, it is a pain to scroll thru.

**Describe the solution you'd like**
Create smaller frozendict files per module and join them together in the main call_schema file.

**Comment by 0x41424142** [comment]
Fixed in [PR 178](https://github.com/0x41424142/qualysdk/pull/178)
